find_package( PkgConfig )

# ilmbase is only pkg-config enabled right now, but
# cmake changes are being submitted to enable a FindIlmBase.cmake
# upon install
find_package( IlmBase QUIET )
if ( IlmBase_FOUND )
message( STATUS "found IlmBase, version ${IlmBase_VERSION}" )
include_directories( ${IlmBase_INCLUDE_DIRS} )
link_directories( ${IlmBase_LIBRARY_DIRS} )
else()
if ( PKG_CONFIG_FOUND )
pkg_check_modules( IlmBase REQUIRED IlmBase )
else()
message( WARNING "Unable to find IlmBase libraries, assuming you have set up a local extra folder with libraries" )
include_directories( "${PROJECT_SOURCE_DIR}/extra/include/OpenEXR" )
link_directories( "${PROJECT_SOURCE_DIR}/extra/lib" )
set( IlmBase_LIBRARIES Imath Half Iex IexMath IlmThread )
if ( WIN32 )
else()
set( IlmBase_LDFLAGS_OTHER pthread )
endif()
endif()
endif()

find_package( libtiff-4 QUIET )
find_package( libtiff QUIET )
#find_package( TIFF QUIET )
if (TIFF_FOUND)
message( STATUS "found TIFF, version ${TIFF_VERSION}" )
else()
if ( PKG_CONFIG_FOUND )
pkg_search_module( TIFF libtiff libtiff-4 )
if (TIFF_FOUND)
message( STATUS "  found TIFF, version ${TIFF_VERSION}" )
endif()
else()
message( WARNING "Unable to find TIFF libraries, disabling" )
endif()
endif()

# openexr is only pkg-config enabled right now, but
# cmake changes are being submitted to enable a FindOpenEXR.cmake
# upon install
find_package( OpenEXR QUIET )
if (OpenEXR_FOUND)
message( STATUS "Found OpenEXR, version ${OpenEXR_VERSION}" )
else()
if ( PKG_CONFIG_FOUND )
pkg_check_modules( OpenEXR OpenEXR )
else()
message( WARNING "Unable to find OpenEXR libraries, disabling" )
endif()
endif()

find_package( AcesContainer )
if (AcesContainer_FOUND)
message( STATUS "Found AcesContainer, version ${AcesContainer_VERSION}" )
else()
if ( PKG_CONFIG_FOUND )
pkg_check_modules( AcesContainer AcesContainer )
else()
message( WARNING "Unable to find AcesContainer libraries, disabling" )
endif()
endif()
